"""
Claude Cross-check Service - Verifies and improves research reports.

Educational Note: This service uses Claude to cross-check research
generated by other providers (like Perplexity) to ensure quality,
accuracy, and clarity.

Cross-check process:
1. Takes draft research report + original topic/description
2. Claude reviews for accuracy, completeness, clarity
3. Identifies questionable claims or contradictions
4. Improves structure and readability
5. Preserves citations and source URLs
"""

from typing import Dict, Any, List
from app.services.integrations.claude import claude_service
from app.config import prompt_loader
from app.utils import claude_parsing_utils


class CrosscheckService:
    """
    Service for cross-checking research reports with Claude.

    Educational Note: Uses Claude to validate and improve research
    from other AI providers, ensuring consistent quality.
    """

    def __init__(self):
        """Initialize with lazy-loaded config."""
        self._prompt_config = None

    def _load_config(self) -> Dict[str, Any]:
        """Lazy load prompt configuration."""
        if self._prompt_config is None:
            self._prompt_config = prompt_loader.get_prompt_config("research_crosscheck")
        return self._prompt_config

    def crosscheck_research(
        self,
        draft_content: str,
        topic: str,
        description: str,
        links: List[str] = None,
        citations: List[str] = None,
        project_id: str = None
    ) -> Dict[str, Any]:
        """
        Cross-check and improve a draft research report using Claude.

        Educational Note: Claude acts as a quality reviewer:
        - Verifies claims are supported
        - Corrects contradictions
        - Improves structure and clarity
        - Preserves citations

        Args:
            draft_content: The draft research text to review
            topic: Original research topic
            description: Research focus areas
            links: Reference links provided by user
            citations: Source URLs from draft research
            project_id: Project ID for cost tracking

        Returns:
            Dict with success status and improved content:
            {
                "success": bool,
                "content": str,        # Improved research text
                "usage": {...},        # Token usage
                "error": str           # Error message if failed
            }
        """
        try:
            config = self._load_config()

            print("[Crosscheck] Starting Claude review of research draft")
            print(f"[Crosscheck] Draft length: {len(draft_content)} chars")

            # Build user message with context
            user_message = self._build_crosscheck_prompt(
                draft_content=draft_content,
                topic=topic,
                description=description,
                links=links,
                citations=citations
            )

            # Call Claude for review
            messages = [{"role": "user", "content": user_message}]

            response = claude_service.send_message(
                messages=messages,
                system_prompt=config["system_prompt"],
                model=config["model"],
                max_tokens=config["max_tokens"],
                temperature=config["temperature"],
                project_id=project_id
            )

            # Extract improved content
            improved_content = claude_parsing_utils.extract_text(response)

            if not improved_content:
                return {
                    "success": False,
                    "error": "Claude returned empty content during cross-check"
                }

            # Track usage
            usage = response.get("usage", {})

            print(f"[Crosscheck] Review complete: {len(improved_content)} chars")

            return {
                "success": True,
                "content": improved_content,
                "usage": usage
            }

        except Exception as e:
            print(f"Cross-check error: {e}")
            return {
                "success": False,
                "error": f"Cross-check failed: {str(e)}"
            }

    def _build_crosscheck_prompt(
        self,
        draft_content: str,
        topic: str,
        description: str,
        links: List[str] = None,
        citations: List[str] = None
    ) -> str:
        """
        Build a comprehensive cross-check prompt for Claude.

        Educational Note: Provides Claude with full context to
        properly review and improve the research.

        Args:
            draft_content: Draft research to review
            topic: Original topic
            description: Research focus
            links: User-provided reference links
            citations: Sources cited in draft

        Returns:
            Formatted prompt string
        """
        prompt_parts = [
            "# Research Cross-Check Task",
            "",
            "## Original Research Request",
            f"**Topic:** {topic}",
            "",
            f"**Focus Areas:** {description}",
            ""
        ]

        # Add reference links if provided
        if links:
            prompt_parts.extend([
                "**Reference Links:**",
                ""
            ])
            for link in links:
                prompt_parts.append(f"- {link}")
            prompt_parts.append("")

        # Add citations from draft
        if citations:
            prompt_parts.extend([
                "**Sources Cited in Draft:**",
                ""
            ])
            for citation in citations[:10]:  # Limit to first 10
                prompt_parts.append(f"- {citation}")
            prompt_parts.append("")

        # Add the draft content
        prompt_parts.extend([
            "## Draft Research Report to Review",
            "",
            "```",
            draft_content,
            "```",
            "",
            "## Your Task",
            "",
            "Please review this research draft and provide an improved version that:",
            "",
            "1. **Verifies Accuracy**: Flag or correct any questionable claims",
            "2. **Improves Clarity**: Enhance structure, flow, and readability",
            "3. **Fills Gaps**: Add important information that's missing",
            "4. **Removes Contradictions**: Resolve any conflicting statements",
            "5. **Preserves Citations**: Keep all source references intact",
            "6. **Professional Quality**: Ensure the final report is publication-ready",
            "",
            "Output the improved research report directly (no meta-commentary)."
        ])

        return "\n".join(prompt_parts)


# Singleton instance
crosscheck_service = CrosscheckService()
